trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - src/*
    - README.md

variables:
- template: variables/core.yml

stages:
- template: stages/build-test-publish-repo.yml
